### ISSUE TITLE
Please import OSC

### ISSUE THREAD

**Issue by scs-yasu** [styly-dev/STYLY-visionOS-Plugin#106]
Hello STYLY team,

I hope this message finds you well. I am currently developing an application for the Apple Vision Pro that aims to synchronize audio and spatial effects. However, I have encountered a limitation regarding MIDI device connectivity.

As it is not physically possible to connect MIDI devices directly to the Vision Pro via USB, I propose an alternative approach. I intend to use TouchDesigner to receive MIDI signals and convert them into OSC (Open Sound Control) messages, which can then be transmitted to and received by the Vision Pro. This method would allow us to effectively integrate MIDI with the Vision Pro, enabling synchronized audio and spatial effects within the application.

To achieve this, I would like to request the implementation of OSC support in the Apple Vision Pro. This feature would greatly enhance the capabilities of the Vision Pro and open up new possibilities for interactive applications that rely on MIDI data.

Thank you for considering this request. I am looking forward to any assistance you can provide in implementing OSC support. Your efforts in making the Vision Pro more versatile and user-friendly are highly appreciated.

https://openupm.com/packages/jp.keijiro.osc-jack/

**Comment by ku6ryo** [comment]
Thank you for your request. We're working on including OSC featrure.

**Comment by scs-yasu** [comment]
Great!! I am looking forward to!!

**Comment by ku6ryo** [comment]
@scs-yasu 
Hi, now STYLY supports receiving OSC message in contents. Please check my simple example to capture how to build content.
https://github.com/ku6ryo/OSC-Sample_STYLY-for-VisionPro

**Comment by scs-yasu** [comment]
wow amazing!!! I wll try!!
