### ISSUE TITLE
Write description about VideoPlayerHelper

### ISSUE THREAD

**Issue by ku6ryo** [styly-dev/STYLY-visionOS-Plugin#118]
Please add description in this page.

https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/wiki/Content-samples#play-online-video

**Comment by DglyP** [comment]
For this description, I created a full documentation on the file and what it does, but I don't think that the wiki is where that description should be added. 

Do you mean a small description of what it does and not a full on documentation?

As I already made it, is there somewhere I can put it for future implementations?

Edit: 
The documentation I talk about is here: https://docs.google.com/document/d/1H61eIY4px7vx-dtzzVWlKChmxBHmSyLwL9mpWEz8Ikw/edit?usp=sharing
